### ISSUE TITLE
Can add parameter clip 2 in vinverse??

### ISSUE THREAD

**Issue by kedaitinh12** [Asd-g/vinverse#1]
I seen script vinverse had clip 2, can you add it in vinverse??
https://github.com/Dogway/Avisynth-Scripts/blob/cb9af65d9711747369815b32f1c4091ef1bf296e/MIX%20mods/QTGMC%2B.avsi#L1409

**Comment by Asd-g** [comment]
You can try the latest version.

**Comment by kedaitinh12** [comment]
It's work, thanks
