### ISSUE TITLE
Adding sbr and sbrV as filters?

### ISSUE THREAD

**Issue by Reel-Deal** [Asd-g/vinverse#3]
Hi Asd,

Thanks for updating this plugin :). I was wondering if you would consider exposing sbr and sbrV as filters? These elemental filters are useful for other tasks also, mainly in pre-filtering. I don't know how much performance there is to gain but back when I asked tp7 to add Vinverse2, I remember the plugin version was reasonably faster than the script version.

**Comment by Asd-g** [comment]
Hi,

You can try the attached file. Only sbrV is included.
```
sbrV (clip input, int "y", int "u", int "v", int "opt")
```

I guess the same function name can be used.

**Comment by Reel-Deal** [comment]
Hi,

I think the same name is appropriate since it can be used as a drop-in replacement. I could of sworn that Vinverse2 also uses sbr(), at least the script version is that way, not sure how it was implemented in the plugin. I may possibly be blind but  I don't see any attached file lol.

**Comment by Asd-g** [comment]
Sorry, I didn't attached the file.

Vinverse2 (the script and plugin) uses only sbrV.

[sbr.zip](https://github.com/Asd-g/vinverse/files/8512565/sbr.zip)

**Comment by Reel-Deal** [comment]
Thanks, I will test it out later on, close to my bedtime.

> Vinverse2 (the script and plugin) uses only sbrV.

Ahh yes - my bad, it's a different part of the [dot crawl script ](https://forum.doom9.org/showpost.php?p=1584186&postcount=62)that uses sbr().

**Comment by Reel-Deal** [comment]
On a synthetic test I get a very nice speed improvement over the script version.

```
ColorBars(1920, 1080, "YV12")
AddGrainC(10000, 10000, seed=1)
sbrV()

Prefetch(4)
```
635fps vs 106fps, thanks Asd! Will this be released as its own separate plugin?

**Comment by Asd-g** [comment]
Yes, I plan to release it as separate plugin.

Btw by default chroma is processed (u/v=3) but in in the script it's copied (u/v=2). I will change it to keep the same behavior by default.

**Comment by Reel-Deal** [comment]
Yes I noticed that after the speed test, U/V=2 was ~100fps faster. Alright, I'll close this issue. Since the performance gap is huge maybe we'll see sbr() also - thanks again :)
