### ISSUE TITLE
white dots with clip2

### ISSUE THREAD

**Issue by realfinder** [Asd-g/vinverse#4]
with samples from https://forum.doom9.org/showpost.php?p=1967847&postcount=913 (amarec(20220418-1636)_sample1.avi and amarec(20220418-1636)_sample2.avi)
```
nnc=nnedi3(-2)
yadifmod2(mode=3, edeint=nnc).Vinverse(clip2=nnc)
```
replace Vinverse with Vinverse_avsi and the problem will gone

**Comment by Dogway** [comment]
Try:
`nnc=nnedi3(-2,range=2)`

**Comment by realfinder** [comment]
that work, so it's full range bug in Vinverse?

**Comment by Dogway** [comment]
probably yes, Vinverse is not clamping values, curious enough this doesn't happen (briefly checked) with nnedi3(-2,range=1) over full range inputs

**Comment by Asd-g** [comment]
Try the latest version.

**Comment by Hackerpcs** [comment]
0.9.4 fixed it, thanks!
